project:
  type: book
  output-dir: docs

book:
  title: "bevezetes_a_mesterseges_intelligenciaba_2026_27_1"
  author: "Norah Jones"
  date: "2026. 09. 10."
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt

editor: visual
