project:
  type: book
  output-dir: docs

book:
  title: "Bevezetés a mesterséges intelligenciába"
  subtitle: "2026/27/1"
  author: "Abari Kálmán"
  date: today
  chapters:
    - index.qmd
    - diasor.qmd
    - digit.qmd
    - alapfogalmak.qmd
    - chatgpt.qmd
    - gemini_notebook.qmd
    - felelos_mi.qmd
    - references.qmd
  appendices:
    - kiseloadas.qmd
    - gyakorlatok.qmd
    - linkek.qmd
    - video_magyarazat.qmd
  
bibliography: references.bib

format:
  html:
    css: css/style.css
    cover-image: cover.png
    theme:
      light: [cosmo, brand]
      dark: [darkly, brand]
  pdf:
    documentclass: scrreprt


published-title: "Utolsó módosítás dátuma"
author-title: "Szerző"
lang: hu
toc-title: "Tartalomjegyzék"
language:
  section-title-appendices: "Függelék"
crossref:
  appendix-title: "Függelék"
