project:
  type: book
  output-dir: docs

book:
  title: "Bevezetés a mesterséges intelligenciába"
  subtitle: "2026/27/1"
  author: "Abari Kálmán"
  date: today
  chapters:
    - index.qmd
    - digit.qmd
    - chatgpt.qmd
    - linkek.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt

editor: visual
